@baseUrl = http://localhost:3000


# POSTS

### 1) Create Post
POST {{baseUrl}}/post
Content-Type: application/json

{
  "senderId": "u1",
  "title": "First Post",
  "content": "Hello from Shir"
}

### 2) Get All Posts
GET {{baseUrl}}/post

### 3) Get Posts By Sender (query param)
GET {{baseUrl}}/post?sender=u1

### 4) Get Post By ID
GET {{baseUrl}}/post/69762c0c5f4ebadc71a7fd13

### 5) Update Post By ID
PUT {{baseUrl}}/post/69762c0c5f4ebadc71a7fd13
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content"
}


# COMMENTS

### Get all comments
GET {{baseUrl}}/comment

###

### Get comments by postId
GET {{baseUrl}}/comment?postId=69762c0c5f4ebadc71a7fd13

###

### Get comment by id
GET {{baseUrl}}/comment/69762e2395f7d2656afc3223

###

### Create comment
POST {{baseUrl}}/comment
Content-Type: application/json

{
  "postId": "69762c0c5f4ebadc71a7fd13",
  "content": "This is a comment",
  "sender": "user456"
}

###

### Update comment
PUT {{baseUrl}}/comment/69762e2395f7d2656afc3223
Content-Type: application/json

{
  "content": "Updated comment content"
}