### Get All Comments
GET http://localhost:3000/comment

### Add a Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "12345",
    "content": "בדיקה מתוך וי אס קוד",
    "sender": "Yael"
}